name: Pull Request - Render Maps
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TIL_JUNE_5 }}
        with:
          filename: template.md